// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_MQOMD9x6xpk-P6m6eC2tXNVk7nEvLU',
    appId: '1:391165729759:web:33dafa0b0bc3e2d3a8826a',
    messagingSenderId: '391165729759',
    projectId: 'airplane-mobile-app',
    authDomain: 'airplane-mobile-app.firebaseapp.com',
    storageBucket: 'airplane-mobile-app.firebasestorage.app',
    measurementId: 'G-4YNHQMP68F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2dJCAdLEJQMAk8kXOq6S--plJR1orhp8',
    appId: '1:391165729759:android:728981f4bb5ae56da8826a',
    messagingSenderId: '391165729759',
    projectId: 'airplane-mobile-app',
    storageBucket: 'airplane-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNpNIGtooU0mYPyBA6zM4jnZH9RXW5Uk',
    appId: '1:391165729759:ios:cd166450e5d7cc5ba8826a',
    messagingSenderId: '391165729759',
    projectId: 'airplane-mobile-app',
    storageBucket: 'airplane-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNpNIGtooU0mYPyBA6zM4jnZH9RXW5Uk',
    appId: '1:391165729759:ios:cd166450e5d7cc5ba8826a',
    messagingSenderId: '391165729759',
    projectId: 'airplane-mobile-app',
    storageBucket: 'airplane-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8_MQOMD9x6xpk-P6m6eC2tXNVk7nEvLU',
    appId: '1:391165729759:web:d8793ecd5bcc79cda8826a',
    messagingSenderId: '391165729759',
    projectId: 'airplane-mobile-app',
    authDomain: 'airplane-mobile-app.firebaseapp.com',
    storageBucket: 'airplane-mobile-app.firebasestorage.app',
    measurementId: 'G-HKDJJW84WP',
  );
}
